(function () {
  const lang = ['ko','en','ja','es'].includes((navigator.language || 'en').toLowerCase().split('-')[0]) ? (navigator.language || 'en').toLowerCase().split('-')[0] : 'en';
  const c = {
    en:{section:'/ MORE FROM LIVE SUB',heading:'One curious mind.<br><em>Seven useful worlds.</em>',intro:'Beyond live streams, we build useful services for the next scene of work and everyday life.',cards:[['01 / LIVE & LANGUAGE','transtream','.app','Real-time translation for global live streams and video calls.'],['02 / EVERYDAY TOOLS','manytool','.net','A collection of small, genuinely useful online tools.'],['03 / WORK & PEOPLE','hireroom','.net','A simple hiring page for small and growing teams.'],['04 / HEALTH & ROUTINE','Healthy','Routine','An app for workout records and routine management.'],['05 / COMMUNITY & CONTENT','SSRRR','.net','Humor, trends, issues and more —<br>all in one community.'],['06 / PROMOTION & DISCOVERY','THE HONGBO','.com','A simple place to promote and<br>discover apps, products and services.'],['07 / QUOTE & MATCHING','MATDA','.net','Post what you need and compare<br>proposals from businesses and professionals.']],cta:['Visit SSRRR','Visit THE HONGBO','Visit MATDA'],chips:['FPS sensitivity','LoL champions','Color picks'],hire:'Product designer',app:'Workout tracker',whyLabel:'/ MADE FOR THE MOMENT',whyTitle:'Keep your eyes<br>on <em>what matters.</em>',whyStat:'languages, one<br>shared experience',whyNote:'Technology can be complex.<br>Connection should feel light.'},
    ko:{section:'/ MORE FROM LIVE SUB',heading:'One curious mind.<br><em>Seven useful worlds.</em>',intro:'라이브를 넘어, 일과 생활의 다음 장면까지.<br>필요한 순간에 필요한 서비스를 만듭니다.',cards:[['01 / LIVE & LANGUAGE','transtream','.app','글로벌 라이브 방송과<br>화상통화를 위한 실시간 번역.'],['02 / EVERYDAY TOOLS','manytool','.net','작지만 확실히 유용한<br>온라인 도구 모음.'],['03 / WORK & PEOPLE','hireroom','.net','중소기업도 쉽게 만드는<br>우리만의 채용 페이지.'],['04 / HEALTH & ROUTINE','헬띠','루틴','운동 기록과<br>루틴 관리를 위한 앱.'],['05 / COMMUNITY & CONTENT','SSRRR','.net','유머부터 이슈·경제까지,<br>가볍게 스르륵 보는 콘텐츠 커뮤니티'],['06 / PROMOTION & DISCOVERY','더홍보','.com','앱부터 상품·서비스까지,<br>누구나 자유롭게 알리는 홍보 플랫폼'],['07 / QUOTE & MATCHING','맡다','.net','필요한 일을 올리고, 업체와 전문가의<br>견적을 비교하는 업무 매칭 플랫폼']],cta:['SSRRR 둘러보기','더홍보 둘러보기','맡다 둘러보기'],chips:['FPS 감도','롤 챔프','컬러 추천'],hire:'Product designer',app:'Workout tracker',whyLabel:'/ MADE FOR THE MOMENT',whyTitle:'Keep your eyes<br>on <em>what matters.</em>',whyStat:'languages, one<br>shared experience',whyNote:'기술은 복잡해도<br>연결은 가벼워야 하니까.'},
    ja:{section:'/ LIVE SUBのプロダクト',heading:'ひとつの好奇心。<br><em>7つの役立つ世界。</em>',intro:'ライブ配信を越えて、仕事と日常の次の場面に役立つサービスを作ります。',cards:[['01 / LIVE & LANGUAGE','transtream','.app','グローバルなライブ配信とビデオ通話のリアルタイム翻訳。'],['02 / EVERYDAY TOOLS','manytool','.net','小さくても確かに役立つオンラインツール集。'],['03 / WORK & PEOPLE','hireroom','.net','中小企業のためのシンプルな採用ページ。'],['04 / HEALTH & ROUTINE','ヘルシー','ルーティン','運動記録とルーティン管理のためのアプリ。'],['05 / COMMUNITY & CONTENT','SSRRR','.net','ユーモアからトレンド・経済まで、<br>気軽に楽しむコンテンツコミュニティ。'],['06 / PROMOTION & DISCOVERY','THE HONGBO','.com','アプリから商品・サービスまで、<br>誰でも気軽に紹介・発見できる場所。'],['07 / QUOTE & MATCHING','MATDA','.net','必要な依頼を投稿して、事業者や専門家の<br>見積もりを比較できるマッチング。']],cta:['SSRRRを見る','THE HONGBOを見る','MATDAを見る'],chips:['FPS感度','LoLチャンピオン','カラー提案'],hire:'Product designer',app:'Workout tracker',whyLabel:'/ MADE FOR THE MOMENT',whyTitle:'大切なものに<br><em>集中しよう。</em>',whyStat:'languages, one<br>shared experience',whyNote:'技術は複雑でも、<br>つながりは軽やかに。'},
    es:{section:'/ MÁS DE LIVE SUB',heading:'Una mente curiosa.<br><em>Siete mundos útiles.</em>',intro:'Más allá de los directos, creamos servicios útiles para el trabajo y la vida diaria.',cards:[['01 / LIVE & LANGUAGE','transtream','.app','Traducción en tiempo real para directos y videollamadas globales.'],['02 / EVERYDAY TOOLS','manytool','.net','Una colección de pequeñas herramientas online realmente útiles.'],['03 / WORK & PEOPLE','hireroom','.net','Una página de contratación sencilla para equipos pequeños.'],['04 / HEALTH & ROUTINE','Healthy','Routine','Una app para registrar entrenamientos y gestionar rutinas.'],['05 / COMMUNITY & CONTENT','SSRRR','.net','Humor, tendencias, temas del momento<br>y más, en una sola comunidad.'],['06 / PROMOTION & DISCOVERY','THE HONGBO','.com','Un lugar sencillo para promocionar y<br>descubrir apps, productos y servicios.'],['07 / QUOTE & MATCHING','MATDA','.net','Publica lo que necesitas y compara<br>propuestas de empresas y profesionales.']],cta:['Visitar SSRRR','Visitar THE HONGBO','Visitar MATDA'],chips:['Sensibilidad FPS','Campeones de LoL','Colores'],hire:'Product designer',app:'Workout tracker',whyLabel:'/ HECHO PARA EL MOMENTO',whyTitle:'Mira lo que<br><em>importa.</em>',whyStat:'languages, one<br>shared experience',whyNote:'La tecnología puede ser compleja.<br>La conexión debe sentirse ligera.'}
  }[lang];
  const q = s => document.querySelector(s);
  const qa = s => document.querySelectorAll(s);
  if (!c || !q('.ecosystem')) return;
  document.querySelector('.ecosystem .section-label').textContent = c.section;
  q('.ecosystem-heading h2').innerHTML = c.heading;
  q('.ecosystem-heading p').innerHTML = c.intro;
  qa('.world-card').forEach((card, i) => { const x=c.cards[i]; card.querySelector('.world-tag').textContent=x[0]; card.querySelector('h3').innerHTML=x[1]+'<span>'+x[2]+'</span>'; card.querySelector('p').innerHTML=x[3]; });
  const chips = q('.tool-chips'); if (chips) chips.innerHTML = c.chips.map(x=>`<span>${x}</span>`).join('');
  qa('.world-cta span').forEach((el, i) => { el.textContent = c.cta[i]; });
  const hire = q('.hire-line span'); if (hire) hire.textContent = c.hire;
  const app = q('.app-line span'); if (app) app.textContent = c.app;
  q('.why .section-label').textContent = c.whyLabel;
  q('.why h2').innerHTML = c.whyTitle;
  q('.why-stat p').innerHTML = c.whyStat;
  q('.why-note p').innerHTML = c.whyNote;
})();
