(function () {
  const lang = ['ko','en','ja','es'].includes((navigator.language || 'en').toLowerCase().split('-')[0]) ? (navigator.language || 'en').toLowerCase().split('-')[0] : 'en';
  const copy = {
    en:{back:'← Back to live sub',kicker:'/ PLATFORM GUIDES',title:'Translate the live web.',lede:'Practical, platform-specific instructions for turning browser audio into real-time multilingual subtitles with Transtream.',cards:[['Chaturbate live translation','How to select browser audio, connect Transtream, choose a language, and troubleshoot captions.'],['Stripchat live translation','A practical setup guide for real-time subtitles while watching a browser-based live stream.'],['SOOP live translation','Translate browser audio from SOOP live streams into real-time subtitles.'],['CHZZK live translation','Set up multilingual captions while watching a CHZZK live stream.'],['YouTube Live translation','Follow YouTube Live streams with real-time translated subtitles.'],['TikTok LIVE translation','Translate TikTok LIVE browser audio into readable subtitles.'],['Twitch live translation','Follow Twitch streams across languages with Transtream captions.']],note:'These are technical setup guides for an independent translation tool. live sub and Transtream are not affiliated with or endorsed by the platforms mentioned.'},
    ko:{back:'← live sub으로 돌아가기',kicker:'/ 플랫폼 가이드',title:'라이브 웹을 번역하세요.',lede:'Transtream으로 브라우저 오디오를 실시간 다국어 자막으로 변환하는 플랫폼별 사용 안내입니다.',cards:[['Chaturbate 라이브 번역','브라우저 오디오를 선택하고 Transtream을 연결해 자막을 설정하는 방법입니다.'],['Stripchat 라이브 번역','브라우저 기반 라이브 방송에서 실시간 자막을 설정하는 방법입니다.'],['SOOP 라이브 번역','SOOP 라이브 방송 오디오를 실시간 자막으로 번역하는 방법입니다.'],['CHZZK 라이브 번역','CHZZK 라이브 방송에서 다국어 자막을 설정하는 방법입니다.'],['YouTube Live 번역','YouTube Live 방송을 실시간 번역 자막과 함께 시청하는 방법입니다.'],['TikTok LIVE 번역','TikTok LIVE 브라우저 오디오를 읽기 쉬운 자막으로 번역합니다.'],['Twitch 라이브 번역','Transtream으로 Twitch 방송을 여러 언어로 시청하는 방법입니다.']],note:'각 가이드는 독립적인 번역 도구의 실제 사용 안내입니다. live sub와 Transtream은 언급된 플랫폼과 제휴하거나 승인받지 않았습니다.'},
    ja:{back:'← live subに戻る',kicker:'/ プラットフォームガイド',title:'ライブウェブを翻訳する。',lede:'ブラウザ音声をリアルタイム多言語字幕に変換するTranstreamのプラットフォーム別ガイドです。',cards:[['Chaturbateライブ翻訳','ブラウザ音声の選択、Transtream接続、字幕設定の手順です。'],['Stripchatライブ翻訳','ブラウザ配信でリアルタイム字幕を使うための設定ガイドです。'],['SOOPライブ翻訳','SOOPライブ配信の音声をリアルタイム字幕に翻訳します。'],['CHZZKライブ翻訳','CHZZKライブ配信で多言語字幕を設定する方法です。'],['YouTube Live翻訳','YouTube Liveをリアルタイム翻訳字幕で視聴する方法です。'],['TikTok LIVE翻訳','TikTok LIVEのブラウザ音声を字幕に変換します。'],['Twitchライブ翻訳','TranstreamでTwitch配信を多言語で視聴する方法です。']],note:'各ガイドは独立した翻訳ツールの技術ガイドです。live subとTranstreamは記載されたプラットフォームと提携・承認されていません。'},
    es:{back:'← Volver a live sub',kicker:'/ GUÍAS DE PLATAFORMAS',title:'Traduce la web en directo.',lede:'Guías prácticas para convertir el audio del navegador en subtítulos multilingües en tiempo real con Transtream.',cards:[['Traducción de Chaturbate','Cómo seleccionar el audio del navegador, conectar Transtream y configurar los subtítulos.'],['Traducción de Stripchat','Guía práctica para usar subtítulos en tiempo real durante un directo.'],['Traducción de SOOP','Convierte el audio de los directos de SOOP en subtítulos en tiempo real.'],['Traducción de CHZZK','Configura subtítulos multilingües para directos de CHZZK.'],['Traducción de YouTube Live','Sigue directos de YouTube Live con subtítulos traducidos.'],['Traducción de TikTok LIVE','Convierte el audio de TikTok LIVE en subtítulos fáciles de leer.'],['Traducción de Twitch','Sigue directos de Twitch en varios idiomas con Transtream.']],note:'Estas guías explican el uso técnico de una herramienta de traducción independiente. live sub y Transtream no están afiliados ni respaldados por las plataformas mencionadas.'}
  }[lang];
  document.documentElement.lang = lang;
  document.title = `${copy.title} | live sub`;
  document.querySelector('.guide-back').textContent = copy.back;
  document.querySelector('.guide-shell>div').textContent = copy.kicker;
  document.querySelector('.guide-shell h1').innerHTML = copy.title.replace(' ', '<br>');
  document.querySelector('.guide-lede').textContent = copy.lede;
  document.querySelectorAll('.guide-card').forEach((card, i) => { card.querySelector('h2').textContent = copy.cards[i][0]; card.querySelector('p').textContent = copy.cards[i][1]; });
  document.querySelector('.guide-note').textContent = copy.note;
})();
